name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 3232
          script: |
            cd /home/minhhan/pwd
            bash update.sh

      - name: Discord Notification
        if: always()
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            COLOR=3066993
            TITLE="✅ Trạng thái Deploy"
          else
            COLOR=15158332
            TITLE="❌ Trạng thái Deploy"
          fi
          
          JSON_PAYLOAD=$(jq -n \
            --arg username "${{ github.repository }} (CI/CD)" \
            --arg title "$TITLE" \
            --argjson color "$COLOR" \
            --arg desc "Dự án: **${{ github.repository }}**\nKết quả: **${{ job.status }}**\nNội dung: **$COMMIT_MSG**\nThực hiện bởi: **${{ github.actor }}**" \
            '{
              username: $username,
              embeds: [{
                title: $title,
                color: $color,
                description: $desc
              }]
            }')
          
          curl -H "Content-Type: application/json" -d "$JSON_PAYLOAD" https://discordapp.com/api/webhooks/1546123810598551652/jFaAxDkyq4cqywUtiw8MJnK_QUt_TBzUjPVc9BpaNvdxMjY4IB0u9v9UVxuam7DYqkKu
