name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 3232
          script: |
            cd /home/minhhan/pwd
            bash update.sh

      - name: Discord Notification
        if: always()
        run: |
          STATUS="${{ job.status }}"
          if [ "$STATUS" = "success" ]; then
            EMOJI="✅"
            TEXT="**THÀNH CÔNG**"
          else
            EMOJI="❌"
            TEXT="**THẤT BẠI**"
          fi
          
          curl -H "Content-Type: application/json" \
               -d '{"content": "'"$EMOJI"' Deploy Kho Mật Khẩu lên VPS '$TEXT'!\n- **Người thực hiện:** ${{ github.actor }}\n- **Link kiểm tra:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
               https://discordapp.com/api/webhooks/1546123810598551652/jFaAxDkyq4cqywUtiw8MJnK_QUt_TBzUjPVc9BpaNvdxMjY4IB0u9v9UVxuam7DYqkKu
